services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=legent_ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: fastapi_backend
    build: ./backend
    ports:
      - "8000:8000"
      - "8080:6080" # noVNC web interface
      - "5900:5900" # VNC port
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
      - ~/.aws:/home/computeruse/.aws # Mount host AWS credentials
    depends_on:
      - db
    restart: always

  frontend:
    container_name: vue_frontend
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
