services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: fastapi_backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
